config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'pages/dashboard'
  end

  resources :payments

  root to: 'pages#welcome'

  namespace :admin do
    resources :dispensaries
    get 'dashboard' => 'pages#dashboard', as: 'dashboard'
  end


  ##### STATIC PAGES #############

  get '/how-it-works' => 'pages#how_it_works', as: 'how_it_works'
  get '/dispensary_information' => 'pages#dispensary_information', as: 'dispensary_information'
  get '/get-started' => 'pages#get_started', as: 'get_started'
  get '/support' => 'pages#support', as: 'support'
  get '/confirm_deal' => 'pages#confirm_deal', as: 'confirm_deal'
  get '/contact' => 'pages#contact', as: 'contact'


  ######## HOOKS ###############################################

  post '/test_purchase_url' => 'pages#test_purchase', as: 'test_purchase'
  #################################
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    get '/dashboard' => 'users#dashboard', as: 'user_dashboard'
    resources :redemptions do
      get '/redeem' => 'redemptions#redeem'
    end
  end


  devise_for :dispensaries, controllers: {registrations: 'dispensaries/registrations'}
  resources :dispensaries do
    resources :deals
    resources :dispensary_rewards
    get '/menu' => 'dispensaries#menu', as: 'menu'
    get '/manage_deals' => 'dispensaries#manage_deals', as: 'manage_deals'
    get '/manage_rewards' => 'dispensaries#manage_rewards', as: 'manage_rewards'

  end



  resources :dispensary_applications
  resources :support_inquiries, except: [:new]


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :loyalty_programs, dependent: :destroy
  has_many :point_buckets, through: :loyalty_programs
  has_many :dispensaries, through: :loyalty_programs  
  has_many :redemptions
  has_many :deals, through: :redemptions
  has_many :payments

  after_create :send_welcome_email

  

  def send_welcome_email
      UserMailer.signup_confirmation(self).deliver
  end

  def has_card?
    self.stripe_customer_token.present?
  end

  def current_card_brand
    if self.payments.present?
      self.payments.last.card_brand
    end
  end

  def current_card_last_4
    if self.payments.present?
      self.payments.last.card_last_4
    end
  end

  def favorite_dispensaries
    dispensaries.sort_by{|d| loyalty_points_for(d)}.reverse.first(5)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_points
    point_buckets.all.sum(:value)
  end

  def point_progress_for(dispensary)
    total_points = loyalty_points_for(dispensary)

    percent = total_points / 100
    return percent *100
  end

  def loyalty_points_for(dispensary)
    loyalty_program_for(dispensary).try(:total_points) || 0
  end

  def loyalty_program_for(dispensary)
    self.loyalty_programs.find_by(dispensary_id: dispensary.id)
  end

  def has_loyalty_program_for?(dispensary)
    self.loyalty_programs.where(:dispensary_id => dispensary.id).present?
  end

  def create_loyalty_program_for(dispensary)
    LoyaltyProgram.create(dispensary_id: dispensary.id, user_id: self.id)
  end
  

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name, :email)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard

  end

  def edit

  end

  def update

  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.erb

app/views/users/show.html.haml
= render '/layouts/search_bar'
.container
  .row.border-bottom.medium-padding-bottom.padding-top
    .col-md-5
      %p.nugdealz-points.green
        = @user.nugdealz_points
      %h2
        = @user.full_name
        %br/
        %small= @user.email
      = link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_user_url(@user), class: 'btn btn-xs btn-default'
    
    .col-md-7.border-left
      %h3 Favorite Dispensaries
      %br/
      - if @user.favorite_dispensaries.present?
        - @user.favorite_dispensaries.each do |d|
          .col-md-10
            %span.lead
              = link_to d.name, dispensary_deals_url(d)
            .progress
              .progress-bar.progress-bar-green{"aria-valuemax" => "420", "aria-valuemin" => "0", "aria-valuenow" => "#{@user.loyalty_points_for(d)}", :role => "progressbar", :style => "width: #{@user.point_progress_for(d)}%"}
          .col-md-2
            %p.progress-bar-points
              = @user.loyalty_points_for(d).round
              %i.fa.fa-fire
      - else
        %p
          %em
            You have no favorites yet, #{link_to "let's fix that!", dispensaries_url}
  .row
    .col-md-12
      %h3 Recent orders
      %br/
      %table.table.table-hover
        %th
          ID
        %th
          Dispensary
        %th
          Deal
        %th
          Date Purchased
        %th
          Status
        %tbody
          - @user.redemptions.each do |r|
            %tr
              %td
                \##{r.id}
              %td
                = link_to r.dispensary.name, dispensary_deals_url(r.dispensary)
              %td
                = r.deal.description
              %td
                = r.created_at.strftime('%m/%d/%y')
              %td
                - if r.redeemed
                  %span.green Redeemed!
                - else
                  %span.text-danger Not Redeemed

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.erb