config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'pages/dashboard'
  end

  resources :payments

  root to: 'pages#welcome'

  namespace :admin do
    resources :dispensaries
    get 'dashboard' => 'pages#dashboard', as: 'dashboard'
  end


  ##### STATIC PAGES #############

  get '/how-it-works' => 'pages#how_it_works', as: 'how_it_works'
  get '/dispensary_information' => 'pages#dispensary_information', as: 'dispensary_information'
  get '/get-started' => 'pages#get_started', as: 'get_started'
  get '/support' => 'pages#support', as: 'support'
  get '/confirm_deal' => 'pages#confirm_deal', as: 'confirm_deal'
  get '/contact' => 'pages#contact', as: 'contact'


  ######## HOOKS ###############################################

  post '/test_purchase_url' => 'pages#test_purchase', as: 'test_purchase'
  #################################
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    get '/dashboard' => 'users#dashboard', as: 'user_dashboard'
    resources :redemptions do
      get '/redeem' => 'redemptions#redeem'
    end
  end


  devise_for :dispensaries, controllers: {registrations: 'dispensaries/registrations'}
  resources :dispensaries do
    resources :deals
    resources :dispensary_rewards
    get '/menu' => 'dispensaries#menu', as: 'menu'
    get '/manage_deals' => 'dispensaries#manage_deals', as: 'manage_deals'
    get '/manage_rewards' => 'dispensaries#manage_rewards', as: 'manage_rewards'

  end



  resources :dispensary_applications
  resources :support_inquiries, except: [:new]


end

app/models/deal.rb
class Deal < ActiveRecord::Base
	belongs_to :dispensary
	has_many :redemptions
  has_many :payments


	scope :recreational, -> {where(recreational: true)}
  scope :medical, -> {where(medical: true)}
	scope :active, -> {where(active: true)}

	def point_value
		(price * 4.20).round(2)
	end



end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # before_filter :set_dispensary

  def show
    @dispensary = Dispensary.find(params[:dispensary_id])
  end

  def index
    @dispensary = Dispensary.find(params[:dispensary_id])

  end

  def new
    @dispensary = Dispensary.find(params[:dispensary_id])
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)

    if @deal.save
      respond_to do |format|
        format.html {redirect_to dispensary_manage_deals_url(@deal.dispensary)}
      end
    end
  end

  def edit
    @deal = Deal.find(params[:id])
    @dispensary = @deal.dispensary
    respond_to :js, :html
  end

  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update(deal_params)
        format.html {redirect_to dispensary_manage_deals_url(@deal.dispensary, @deal), notice: 'Deal Successfully Updated.'}
      else
        format.html {redirect_to :back, notice: "Something didn't work there"}
      end
    end
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def deal_params
    params.require(:deal).permit(:title, :description, :fine_print, :quantity_available, :price, :dispensary_id, :recreational, :medical)
  end

  # def set_dispensary

  # end

end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.haml
= form_for [@dispensary, @deal] do |f|
  = f.hidden_field :dispensary_id, value: @dispensary.id
  .form-group.col-md-12
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group.col-md-12
    = f.label :description
    = f.text_field :description, class: 'form-control'
  .form-group.col-md-12
    = f.label :fine_print
    = f.text_field :fine_print, class: 'form-control'
  .form-group.col-md-6
    = f.label :price
    = f.number_field :price, class: 'form-control', step: 0.01, min: 0
  .form-group.col-md-6
    = f.label :quantity_available
    = f.number_field :quantity_available, class: 'form-control', min: 0, step: 1
  .form-group.col-md-6
    = f.check_box :active
    = f.label :active?

  .col-md-12
    = f.submit 'Save', class: 'btn btn-green'

app/views/deals/_hybrid.html.haml
.row
  .col-md-6
    %h2 Medical Dealz
    - @dispensary.deals.medical.each do |deal|
      .row.border-bottom.padding-top
        %h3.text-left= deal.title
        .col-md-2.text-center
          %p
            %span.point-value= deal.point_value
            %br/
            points
        .col-md-8
          %p.lead
            = deal.description
            %b
              (#{deal.quantity_available} left)
        .col-md-2
          %center
            = link_to 'Redeem', confirm_deal_url(deal: deal.id), class: 'btn btn-default btn-xs'
  .col-md-6.border-left
    %h2.text-right Recreational
    - @dispensary.deals.recreational.each do |deal|
      .row.border-bottom.padding-top
        %h3.text-right= deal.title
        .col-md-2
          %center
            = link_to 'Redeem', confirm_deal_url(deal: deal.id), class: 'btn btn-default btn-xs'
        .col-md-8
          %p.lead
            = deal.description
            %b
              (#{deal.quantity_available} left)
        .col-md-2.text-center
          %p
            %span.point-value= deal.point_value
            %br/
            points

app/views/deals/_single.html.haml
.row
  .col-md-8.col-md-offset-2.padding-top
    - @dispensary.deals.each do |deal|
      .row.deal-well
        .col-md-2.text-center.padding-top
          %p
            %span.point-value= number_to_currency(deal.price)
          %P            
            (#{deal.point_value} points)
        .col-md-10.border-left.medium-padding-top
          =image_tag 'highlight.png', class: 'pull-right highlighter hidden'
          %b.lead
            %b= deal.title
          %p          
            = deal.description
          %p
            = link_to "#{deal.quantity_available} left", confirm_deal_url(deal: deal.id), class: 'btn btn-clear-pink'
            = link_to 'Redeem', confirm_deal_url(deal: deal.id), class: 'btn btn-green'
        
          

app/views/deals/create.html.haml
%h1 Deals#create
%p Find me in app/views/deals/create.html.erb

app/views/deals/destroy.js.erb
$('#deal_<%= @deal.id %>').fadeOut();

app/views/deals/edit.html.haml
.container
  .row
    .col-md-6
      %h3 Edit Deal
      %p.lead Use the form on the right to edit the deal. This is where you can deactive or increase the quantity of the deal! Click save when you are finished.
    .col-md-5.col-md-offset-1
      = render 'form'

app/views/deals/index.html.haml
#dispensary-header
  .container
    .row.medium-padding-bottom
      .col-md-12
        %h1#dispensary-title.white
          = @dispensary.name
          %address
            %small
              = @dispensary.address1
              - if @dispensary.address2.present?
                = @dispensary.address2
              = @dispensary.city
              , #{@dispensary.state} #{@dispensary.zip}
        - if current_dispensary && current_dispensary == @dispensary
          = link_to '<i class="fa fa-plus"></i> Add a Deal'.html_safe, new_dispensary_deal_url(@dispensary), class: 'btn btn btn-green'
          = link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe, dispensary_url(@dispensary), class: 'btn btn btn-default'

#deals.container
  - if @dispensary.recreational && @dispensary.medical
    = render 'hybrid'
  - else
    = render 'single'

app/views/deals/new.html.haml
.container
  .row
    .col-md-6
      %h3 Create a Deal
      %p.lead Use the form to the right to create your deal. Remember, these deals should be the best deals you can offer. We want customers to spread the word!
    .col-md-5.col-md-offset-1
      = render 'form'

app/views/deals/show.html.haml
%h1 Deals#show
%p Find me in app/views/deals/show.html.erb

app/views/deals/single.html.haml
.row
  .col-md-8.col-md-offset-2.left-right-border
    - @dispensary.deals.each do |deal|
      .row.border-bottom.padding-top
        %h3.text-center.green= deal.title
        .col-md-2.text-center
          %p
            %span.point-value= deal.point_value
            %br/
            points
        .col-md-8
          %p.lead
            = deal.description
            %b
              (#{deal.quantity_available} left)
        .col-md-2
          = link_to 'Redeem', confirm_deal_url(deal: deal.id), class: 'btn btn-default btn-block'