config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'pages/dashboard'
  end

  resources :payments

  root to: 'pages#welcome'

  namespace :admin do
    resources :dispensaries
    get 'dashboard' => 'pages#dashboard', as: 'dashboard'
  end


  ##### STATIC PAGES #############

  get '/how-it-works' => 'pages#how_it_works', as: 'how_it_works'
  get '/dispensary_information' => 'pages#dispensary_information', as: 'dispensary_information'
  get '/get-started' => 'pages#get_started', as: 'get_started'
  get '/support' => 'pages#support', as: 'support'
  get '/confirm_deal' => 'pages#confirm_deal', as: 'confirm_deal'
  get '/contact' => 'pages#contact', as: 'contact'


  ######## HOOKS ###############################################

  post '/test_purchase_url' => 'pages#test_purchase', as: 'test_purchase'
  #################################
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    get '/dashboard' => 'users#dashboard', as: 'user_dashboard'
    resources :redemptions do
      get '/redeem' => 'redemptions#redeem'
    end
  end


  devise_for :dispensaries, controllers: {registrations: 'dispensaries/registrations'}
  resources :dispensaries do
    resources :deals
    resources :dispensary_rewards
    get '/menu' => 'dispensaries#menu', as: 'menu'
    get '/manage_deals' => 'dispensaries#manage_deals', as: 'manage_deals'
    get '/manage_rewards' => 'dispensaries#manage_rewards', as: 'manage_rewards'

  end



  resources :dispensary_applications
  resources :support_inquiries, except: [:new]


end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessor :stripe_card_token

  belongs_to :user
  belongs_to :deal


  def save_with_payment
    if valid?
      if self.user.stripe_customer_token
        customer = Stripe::Customer.retrieve(self.user.stripe_customer_token)
      else
        customer = Stripe::Customer.create(description: "#{self.user.full_name}", card: stripe_card_token)
        self.user.stripe_customer_token = customer.id
        self.user.save
      end
      charge = Stripe::Charge.create(customer: customer.id, currency: 'usd', amount: amount.to_i, description: "#{self.user.full_name}")
      self.charge_token = charge.id
      self.card_last_4 = charge.source.last4
      self.card_brand = charge.source.brand
      self.description = "Deal #{self.deal.id} - #{self.deal.title}"
      save!
    end

    rescue Stripe::InvalidRequestError => e
      logger.error "Stripe error while creating payment: #{e.message}"
      errors.add :base, "There was a problem charging your credit card."
      false
  end



end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    user_id = params[:payment][:user_id]
    @user = User.find(user_id)
    deal_id = params[:payment][:deal_id]
    @deal = Deal.find(deal_id)
    dispensary_id = params[:payment][:dispensary_id]
    @dispensary = Dispensary.find(dispensary_id)
    respond_to do |format|
      if @payment.save_with_payment
        Redemption.create(user_id: user_id, deal_id: deal_id, dispensary_id: dispensary_id)
        @dispensary.complete_order_for(@deal)
        format.html { redirect_to user_url(@user), notice: 'You have successfully redeemed your deal, check your email for instructions.'}
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { redirect_to :back, notice: "Oops, that didn't work. Please try again." }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:stripe_card_token, :user_id, :amount, :deal_id, :charge_token, :card_last_4, :card_brand, :description, :created_at, :updated_at)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
= form_for(@payment) do |f|
  - if @payment.errors.any?
    #error_explanation
      %h2
        = pluralize(@payment.errors.count, "error")
        prohibited this payment from being saved:
      %ul
        - @payment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :amount
    %br/
    = f.number_field :amount
  .field
    = f.label :deal_id
    %br/
    = f.number_field :deal_id
  .field
    = f.label :charge_token
    %br/
    = f.text_field :charge_token
  .field
    = f.label :card_last_4
    %br/
    = f.text_field :card_last_4
  .field
    = f.label :card_brand
    %br/
    = f.text_field :card_brand
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :created_at
    %br/
    = f.text_field :created_at
  .field
    = f.label :updated_at
    %br/
    = f.text_field :updated_at
  .actions
    = f.submit

app/views/payments/edit.html.haml
%h1 Editing payment
= render 'form'
= link_to 'Show', @payment
|
= link_to 'Back', payments_path

app/views/payments/index.html.haml
%h1 Listing payments
%table
  %thead
    %tr
      %th User
      %th Amount
      %th Deal
      %th Charge token
      %th Card last 4
      %th Card brand
      %th Description
      %th Created at
      %th Updated at
      %th{:colspan => "3"}
  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.user_id
        %td= payment.amount
        %td= payment.deal_id
        %td= payment.charge_token
        %td= payment.card_last_4
        %td= payment.card_brand
        %td= payment.description
        %td= payment.created_at
        %td= payment.updated_at
        %td= link_to 'Show', payment
        %td= link_to 'Edit', edit_payment_path(payment)
        %td= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Payment', new_payment_path

app/views/payments/new.html.haml
%h1 New payment
= render 'form'
= link_to 'Back', payments_path

app/views/payments/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @payment.user_id
%p
  %strong Amount:
  = @payment.amount
%p
  %strong Deal:
  = @payment.deal_id
%p
  %strong Charge token:
  = @payment.charge_token
%p
  %strong Card last 4:
  = @payment.card_last_4
%p
  %strong Card brand:
  = @payment.card_brand
%p
  %strong Description:
  = @payment.description
%p
  %strong Created at:
  = @payment.created_at
%p
  %strong Updated at:
  = @payment.updated_at
= link_to 'Edit', edit_payment_path(@payment)
|
= link_to 'Back', payments_path